# ===========================================================================
#  Copyright © 2014  CS -  All rights reserved.
# ===========================================================================

CXX    := g++
CFLAGS := -std=gnu++11 -Wall -Wextra -I ../lib

all:
	$(CXX) $(CFLAGS) ./*.cpp ../lib/can.cpp  -o aufgabe.elf

clean:
	rm -v ./aufgabe.elf
